# GitHub Configuration
github:
  username: "subhro01"        # Replace with your GitHub username
  password: "Subhro@81094"        # Replace with your GitHub password
  owner: "valid_owner"              # Replace with the owner of the repository
  repository_name: "test-repo"      # Replace with the name of the repository to create
  repository_description: "This is a test repository"  # Description of the test repo
  repository_visibility: true       # Set to true for private repo, false for public repo
  api_token: "your_personal_access_token"

# WebDriver Configuration
webdriver:
  browser: "chrome"                 # Specify the browser to use ('chrome', 'firefox', etc.)
  implicit_wait: 10                 # Implicit wait time in seconds

# Test Report Configuration
report:
  log_file: "./logs/test_log.log"   # Path to save the log file
  report_dir: "./logs"              # Directory to save the HTML report
